variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
    - build
    - test
    - package
    - deploy


cache:
  paths:
    - .m2/repository
    - target

build_job:
  stage: build
  tags:
    - docker 

  script: 
    - echo "Maven compile started"
    - "mvn compile"


test_job:
  stage: test
  tags:
    - docker 

  script: 
    - echo "Maven test started"
    - "mvn test"

package_job:
  stage: package
  tags:
    - docker 

  script: 
    - echo "Maven packaging started"
    - "mvn package"


Deploy_job:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script: 
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@157.245.51.174 "cd /opt/tomcat/webapps/g6 && git pull && mvn compile package && rm -R /opt/tomcat/webapps/ROOT/ && cp -R /opt/tomcat/webapps/g6/target/training_support_system-1.0.0 /opt/tomcat/webapps && mv /opt/tomcat/webapps/training_support_system-1.0.0 /opt/tomcat/webapps/ROOT && rm /opt/tomcat/webapps/ROOT/WEB-INF/classes/db.properties && cp /opt/tomcat/webapps/db.properties /opt/tomcat/webapps/ROOT/WEB-INF/classes && echo Done"
